### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by phpManiac77** [basz/zf2-module-phing-service#1]
This method causes that it does not work on windows. 

```
protected function doBuild($target, PhingOptions $options)
{
    if (!self::hasExec()) {
        throw new \RuntimeException("Not able to use PHP's exec method");
    }

    $commands = $this->getEnvironmentCommands();

    $commands[] = sprintf("%s %s \\\n      %s 2>&1 ", $this->options->getPhingBin(), implode(" \\\n      ", $this->getPhingCommandArgumentsArray($options)), $target);

    $command = implode(" && \\\n", $commands);

    exec($command, $output, $return_status);

    return array('command' => $command, 'output' => implode(PHP_EOL, $output), 'returnStatus' => $return_status);
}
```

Windows can not execute commands concated in this way.

**Comment by basz** [comment]
Hi! Are you able to change this in a pull request?

**Comment by phpManiac77** [comment]
Hi,

I'm comletly new at github.

What is a pull request.

Best regards

Damir Abdijevic

Damir Abdijevic
Siebenschön 3
22529 Hamburg
Telefon:      +49(0)40/525 90 979
Fax:          +49(0)40/525 90 980
Handy:        +49(0)162/918 53 00
Handy:        +49(0)176/724 852 15
E-Mail:       damir.abdijevic@finait.de
Skype:        finait.de
Web-Seite:    http://www.finait.de
Steuernummer: 45/001/01658
UstId:        DE287623857

Am 29.01.2015 um 20:20 schrieb Bas Kamer:

**Comment by basz** [comment]
Ah no problem, I'll reopen this issue. and try to change it myself anytime soon.

A PR is a a change in code in a repository that you would clone from this one. Then I would able to review that change in the code and merge into the main repository...

**Comment by phpManiac77** [comment]
```
protected function doBuild($target, PhingOptions $options)
{
    if (!self::hasExec()) {
        throw new \RuntimeException("Not able to use PHP's exec method");
    }
    foreach ($this->getEnvironmentCommands() as $envCommand) {
        passthru($envCommand);
    }

    $command = sprintf("%s %s %s ", $this->options->getPhingBin(), implode(" ", $this->getPhingCommandArgumentsArray($options)), $target);

    exec($command, $output, $return_status);

    return array('command' => $command, 'output' => implode(PHP_EOL, $output), 'returnStatus' => $return_status);
}
```

A quick fix. Will work on both platforms.

**Comment by phpManiac77** [comment]
Maybe also putting file pathes into double qoutes might be good to avoid problems with space characters. Maybe something like this:

```
protected function getEnvironmentCommands()
{
    $commands = array();

    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        $commands[] = sprintf('set PHP_COMMAND="%s"', $this->options->getPhpBin());
        $commands[] = sprintf('set PHING_HOME="%s"', $this->options->getPhingPath());
        $commands[] = sprintf('set PHP_CLASSPATH="%s\classes"', $this->options->getPhingPath());
        $commands[] = 'set PATH=%PATH%;"%PHING_HOME%\bin"';
    } else {
        $commands[] = sprintf('export PHP_COMMAND="%s"', $this->options->getPhpBin());
        $commands[] = sprintf('export PHING_HOME="%s"', $this->options->getPhingPath());
        $commands[] = 'export PHP_CLASSPATH="${PHING_HOME}/classes"';
        $commands[] = 'export PATH=${PATH}:"${PHING_HOME}/bin"';
    }

    return $commands;
}
```

**Comment by basz** [comment]
hi, I've made some changes.

would you be able to test upgrading to ~1.1@dev? and let me know if things  work as expected...

Via composer upgrading is trivial

**Comment by phpManiac77** [comment]
Thanks, but I have an own solution and don't need a complete module for phing. Setting phing environment variables only one time (permanently)  and using ZF2, making an action that receives options for phing and passing it to a phing call is enough.

**Comment by basz** [comment]
ok no problem...

For your information, I'll be releasing a rewrite 2.0 soon that should fix the above issue. It simplifies things a little bit further. It will rely on Symphony's Process abstraction for the actual running of Phing and will come with unittests.
